### ISSUE TITLE
Investigate networking for the pi

### ISSUE THREAD

**Issue by kragniz** [abersailbot/dewi#7]
We currently have a wifi router sitting in Dewi. This should be replaced with a wifi antenna (abersailbot/dewi-hardware#38), but what will the connectivity look like in its place?

Options include, but are not limited to:
- Dewi's pi hosting a wifi hotspot
- Dewi's pi connecting to eduroam (requires an account, so reliant on IS)
- Dewi's pi connecting to a wifi network we configure ourselves (like the old kitty setup)
- Dewi's pi connecting via ethernet to something
- Tethering dewi's pi to a mobile and connecting that to either wifi or 3g

Things to consider are deploying code and debugging in the field.

**Comment by LandingEllipse** [comment]
I don't know if this has been settled yet. If not then with the goal being to give the pi access to the internet when appropriate, and additionally have it accessible over ssh, I have a few thoughts on this:

Eduroam can be very frustrating to use in this scenario because while you get access to the internet, what subnet you end up on and which "local" IPs you are able to resolve  (goal: the IP of your workstation) appears to depend on dark magic. You could pull a stunt with a reverse port forward via ssh, but then you would be dependent on an external server and incur a response time penalty. Also restricts access to those who have access and the know-how to go through the server.

Having the PI act as a hotspot gives easy ssh access, but leaves you with no gateway to the lulz of the internet. Can be handy as a fallback mode in the field though I guess.

What I have ended up doing in a similar setting is get a [GL-AR150 ](http://www.amazon.co.uk/gp/product/B015CYI8DY?ref_=pe_385721_51767431_TE_dp_1) (openwrt ftw) and set up a network that all interested parties can connect to, including the PI (auto-retry from startup). 
The GL's WAN port is hooked up to my laptop's ethernet port which is set to act as gateway to the laptop's wifi, aka eduroam.
This sounds a lot like your third alternative, so I am curious if there was anything with kitty's old setup that has made this a less attractive solution?

**Comment by TomGC96** [comment]
Dewi is now hosting an access point via a USB WiFi adapter allowing us to connect and use SSH. However this does not allow us access to the internet via the Pi. abersailbot/dewi-hardware#38

**Comment by Danyc0** [comment]
So the current Pi setup is that if it can see a second USB wifi dongle (along side the one hosting the AP), it'll use that to connect to an AP called "TomAberSailbot" (which should really go in a config file, but isn't for the moment) and get internet that way. The correct password for "TomAberSailbot" needs to be set in dewi/etc/password before running the provisioner.

**Comment by TomGC96** [comment]
I thought you'd removed that after Dewi's AP was working, apologies!

**Comment by Danyc0** [comment]
The second wifi dongle is removed, but the code still exists, so to get internet, just create the "TomAberSailbot" AP with WPA, and plug a second wifi dongle into the Pi
